name: Flake check
on: pull_request
jobs:
  checks:
    name: Flake checks on ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [aarch64-darwin]
    steps:
      - uses: actions/checkout@v5
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v12
